/*
 * printf_config.h
 *
 *  Created on: Jun 18, 2023
 *      Author: rini
 */

#ifndef INC_PRINTF_CONFIG_H_
#define INC_PRINTF_CONFIG_H_

#define SUPPORT_MSVC_STYLE_INTEGER_SPECIFIERS		0
#define PRINTF_SUPPORT_LONG_LONG					0
#define PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS		0
#define PRINTF_SUPPORT_WRITEBACK_SPECIFIER			0

#endif /* INC_PRINTF_CONFIG_H_ */
